export const testWeatherArr = {
  forecast: {
    forecastday: [
      {
        date: '2023-11-28',
        date_epoch: 1701129600,
        day: {
          maxtemp_c: 9.8,
          maxtemp_f: 49.7,
          mintemp_c: -0.6,
          mintemp_f: 30.9,
          avgtemp_c: 5.1,
          avgtemp_f: 41.1,
          maxwind_mph: 37.8,
          maxwind_kph: 60.8,
          totalprecip_mm: 7.62,
          totalprecip_in: 0.3,
          totalsnow_cm: 0,
          avgvis_km: 9.8,
          avgvis_miles: 6,
          avghumidity: 79,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 93,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Moderate rain',
            icon: '//cdn.weatherapi.com/weather/64x64/day/302.png',
            code: 1189,
          },
          uv: 2,
        },
        astro: {
          sunrise: '07:16 AM',
          sunset: '04:13 PM',
          moonrise: '04:36 PM',
          moonset: '08:38 AM',
          moon_phase: 'Waning Gibbous',
          moon_illumination: 99,
          is_moon_up: 1,
          is_sun_up: 0,
        },
      },
      {
        date: '2023-11-28',
        date_epoch: 1701129600,
        day: {
          maxtemp_c: 9.8,
          maxtemp_f: 49.7,
          mintemp_c: -0.6,
          mintemp_f: 30.9,
          avgtemp_c: 5.1,
          avgtemp_f: 41.1,
          maxwind_mph: 37.8,
          maxwind_kph: 60.8,
          totalprecip_mm: 7.62,
          totalprecip_in: 0.3,
          totalsnow_cm: 0,
          avgvis_km: 9.8,
          avgvis_miles: 6,
          avghumidity: 79,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 93,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Moderate rain',
            icon: '//cdn.weatherapi.com/weather/64x64/day/302.png',
            code: 1189,
          },
          uv: 2,
        },
        astro: {
          sunrise: '07:16 AM',
          sunset: '04:13 PM',
          moonrise: '04:36 PM',
          moonset: '08:38 AM',
          moon_phase: 'Waning Gibbous',
          moon_illumination: 99,
          is_moon_up: 1,
          is_sun_up: 0,
        },
      },
      {
        date: '2023-11-28',
        date_epoch: 1701129600,
        day: {
          maxtemp_c: 9.8,
          maxtemp_f: 49.7,
          mintemp_c: -0.6,
          mintemp_f: 30.9,
          avgtemp_c: 5.1,
          avgtemp_f: 41.1,
          maxwind_mph: 37.8,
          maxwind_kph: 60.8,
          totalprecip_mm: 7.62,
          totalprecip_in: 0.3,
          totalsnow_cm: 0,
          avgvis_km: 9.8,
          avgvis_miles: 6,
          avghumidity: 79,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 93,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Moderate rain',
            icon: '//cdn.weatherapi.com/weather/64x64/day/302.png',
            code: 1189,
          },
          uv: 2,
        },
        astro: {
          sunrise: '07:16 AM',
          sunset: '04:13 PM',
          moonrise: '04:36 PM',
          moonset: '08:38 AM',
          moon_phase: 'Waning Gibbous',
          moon_illumination: 99,
          is_moon_up: 1,
          is_sun_up: 0,
        },
      },
      {
        date: '2023-11-28',
        date_epoch: 1701129600,
        day: {
          maxtemp_c: 9.8,
          maxtemp_f: 49.7,
          mintemp_c: -0.6,
          mintemp_f: 30.9,
          avgtemp_c: 5.1,
          avgtemp_f: 41.1,
          maxwind_mph: 37.8,
          maxwind_kph: 60.8,
          totalprecip_mm: 7.62,
          totalprecip_in: 0.3,
          totalsnow_cm: 0,
          avgvis_km: 9.8,
          avgvis_miles: 6,
          avghumidity: 79,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 93,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Moderate rain',
            icon: '//cdn.weatherapi.com/weather/64x64/day/302.png',
            code: 1189,
          },
          uv: 2,
        },
        astro: {
          sunrise: '07:16 AM',
          sunset: '04:13 PM',
          moonrise: '04:36 PM',
          moonset: '08:38 AM',
          moon_phase: 'Waning Gibbous',
          moon_illumination: 99,
          is_moon_up: 1,
          is_sun_up: 0,
        },
      },
      {
        date: '2023-11-28',
        date_epoch: 1701129600,
        day: {
          maxtemp_c: 9.8,
          maxtemp_f: 49.7,
          mintemp_c: -0.6,
          mintemp_f: 30.9,
          avgtemp_c: 5.1,
          avgtemp_f: 41.1,
          maxwind_mph: 37.8,
          maxwind_kph: 60.8,
          totalprecip_mm: 7.62,
          totalprecip_in: 0.3,
          totalsnow_cm: 0,
          avgvis_km: 9.8,
          avgvis_miles: 6,
          avghumidity: 79,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 93,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Moderate rain',
            icon: '//cdn.weatherapi.com/weather/64x64/day/302.png',
            code: 1189,
          },
          uv: 2,
        },
        astro: {
          sunrise: '07:16 AM',
          sunset: '04:13 PM',
          moonrise: '04:36 PM',
          moonset: '08:38 AM',
          moon_phase: 'Waning Gibbous',
          moon_illumination: 99,
          is_moon_up: 1,
          is_sun_up: 0,
        },
      },
      {
        date: '2023-11-28',
        date_epoch: 1701129600,
        day: {
          maxtemp_c: 9.8,
          maxtemp_f: 49.7,
          mintemp_c: -0.6,
          mintemp_f: 30.9,
          avgtemp_c: 5.1,
          avgtemp_f: 41.1,
          maxwind_mph: 37.8,
          maxwind_kph: 60.8,
          totalprecip_mm: 7.62,
          totalprecip_in: 0.3,
          totalsnow_cm: 0,
          avgvis_km: 9.8,
          avgvis_miles: 6,
          avghumidity: 79,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 93,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Moderate rain',
            icon: '//cdn.weatherapi.com/weather/64x64/day/302.png',
            code: 1189,
          },
          uv: 2,
        },
        astro: {
          sunrise: '07:16 AM',
          sunset: '04:13 PM',
          moonrise: '04:36 PM',
          moonset: '08:38 AM',
          moon_phase: 'Waning Gibbous',
          moon_illumination: 99,
          is_moon_up: 1,
          is_sun_up: 0,
        },
      },
    ]
  },
};
